---
title: Mustang Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: 
email: 
description: ''
twitter_username: 
github_username: jekyll
rss: 
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
